[defaults]
rsync = ["-a", "-i", "-v", "-h"]
robocopy = ["/E", "/DCOPY:DAT", "/COPY:DAT", "/R:3", "/W:1", "/NDL"]

[backup]
rsync = ["-a", "-i", "-v", "-h"]
robocopy = ["/E", "/DCOPY:DAT", "/COPY:DAT", "/R:3", "/W:1", "/NDL"]

[mirror]
rsync = ["-a", "-i", "-v", "-h"]
robocopy = ["/E", "/DCOPY:DAT", "/COPY:DAT", "/R:3", "/W:1", "/NDL"]

[incremental]
rsync = ["-a", "-i", "-v", "-h"]
robocopy = ["/E", "/DCOPY:DAT", "/COPY:DAT", "/R:3", "/W:1", "/NDL"]
